export const ActionTypes = {
    CREATE_TASK: "CREATE_TASK",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
    CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",
    EDIT_TASK: "EDIT_TASK",
    EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCESS",
    EDIT_TASK_FAILURE: "EDIT_TASK_FAILURE",
    SET_TASKS: "SET_TASKS",
    SELECTED_TASK: "SELECTED_TASK",
    REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
    SET_CURRENT_TASK: "SET_SURRENT_TASK",
    SET_CURRENT_OPERATION: "SET_CURRENT_OPERATION",
};